name: Deploy front-end to dev environment

on:
    push:
        branches: [dev, main]
    workflow_dispatch:

env:
    PROJECT_NUMBER: 944098180338
    PROJECT_ID: questao
    SERVICE: adouropreto-web
    REGION: us-east1

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: "read"
            id-token: "write"

        steps:
            - name: "Checkout code"
              uses: "actions/checkout@v4"
              with:
                  ref: dev

            - name: "Authenticate in Google Cloud"
              id: auth
              uses: "google-github-actions/auth@v1"
              with:
                  workload_identity_provider: "projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/pool/providers/github"
                  service_account: "${{ env.PROJECT_NUMBER }}-compute@developer.gserviceaccount.com"
                  project_id: ${{ env.PROJECT_ID }}
                  token_format: access_token

            - name: Docker Auth
              id: docker-auth
              uses: "docker/login-action@v3"
              with:
                  registry: "${{ env.REGION }}-docker.pkg.dev"
                  username: oauth2accesstoken
                  password: ${{ steps.auth.outputs.access_token }}

            - name: Build, tag and push container
              id: build-image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/docker/${{ env.SERVICE }}:${{  github.sha }}"

            - name: "Deploy Cloud Run"
              id: "deploy"
              uses: "google-github-actions/deploy-cloudrun@v1"
              with:
                  service: ${{ env.SERVICE }}
                  region: ${{ env.REGION }}
                  image: "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/docker/${{ env.SERVICE }}:${{  github.sha }}"
                  flags: --allow-unauthenticated
